### ISSUE TITLE
Write Process section into eve.html - Eve

### ISSUE THREAD

**Issue by mariannegoldin** [josephwanderer/itc134fl17-waffle-pie#6]

**Comment by DonutSSS** [comment]
I should edit eve.html in Eve's branch and then merge it with eve.html under master branch. You can always see my latest vision in master branch. Then we could merge our work together in index.html under master branch to avoid the conflicts.

**Comment by mariannegoldin** [comment]
Thanks Eve! You section has been merged into the index.html file
